language: node_js
node_js:
  - "8.11.3"
notifications:
  email: false
after_success:
  - npm run coverage
services:
    - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres