language: node_js
node_js:
  - "8.11.3"
notifications:
  email: false
after_success:
  - npm run coverage
services:
    - postgresql
before_script:
 - psql -c "CREATE DATABASE testing_db;" -U postgres
 - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres